### ISSUE TITLE
[NEW USER] Shelley McCann

### ISSUE THREAD

**Issue by shmccann** [Klepac-Ceraj-Lab/klepac-ceraj-lab.github.io#2]
Please see the [SSH setup page](https://klepac-ceraj-lab.github.io/drylab/ssh/) for more information.

Please fill out the following - 

- **Name**: Shelley McCann
- **Wellesley email**: sm106@wellesley.edu
- **Requested username**: shelley
- **Server(s) you need access to**:
  - [x] `ada`
  - [ ] `hopper`
  - [ ] `rosalind`

Paste your public key (eg `ada-key.pub` bellow between the backticks. If you need access to multiple servers, please use a separate key for each.

```
AAAAB3NzaC1yc2EAAAADAQABAAABgQC56EHC/uDfylLxXzLy6FX09q/vzihRb0tYOVVq7rVg33TwJn+yrMmiW6/Lrw3lgPO0N9AhZ/Y5mxxdUasQEqywMdmro3ANr7H56kGZ9x3ZqWW9NF9mKSsFFKKANwpFmyno8f1VTpwBrxce4ctB2wuqVYOJc8J6Mb73jZwyRO8Fr9v1F0xqgEyahOl4btbm5lz6CYE8q1tcqcsfJxdcvs8m/LB2e0+LHBLu0gK4ywbKfvApbHv6dtKNosGN7OIcwStbumfZgEw7f2fJs5RL4PppfubuWE5FLjHlICUnlkUJzjRvX+W46kBsqFix7tusYSxgfDLU8Ng5+pf/276HcJGhwA1tc1Xe8YCxpKoB1HBdjKKuNnGFQMdx+8dcWxjf2How7haiTxpXI++mQCIry8o1BRSclW/cA9sH7CFR48/Cg3yyWsbHs8Bh3R2nmPJW418+DXPDD/iq57rMtFG/zmezpM6Wk1LjwHcgVGuEPTbhtmsGi+neSwnEmuJQROvCVOM= sm106@FS-FV-sm106-mbp-0820
```

**Comment by kescobo** [comment]
Account created and key added (I'll let you know when the last part of the tutorial is ready.
